# config.yml
# app configuration

smtp:
  server: smtp-server
  port: 9527
  user: smtp-user
  passwd: smtp-pass
  mailto: mail-receiver

# add urls below
feed:
  - name: kaif.io
    url: https://kaif.io/hot.rss
    handleTime: 2021-06-18 14:15:16
    checksum: xxx
    result: OK
  - name: ithome
    url: https://www.ithome.com.tw/rss
    handleTime: 2021-06-18 14:15:16
    checksum: xxx
    result: OK
