# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI 

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
  pull_request:
    branches: 
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Keep one artifact
      run: rm original-*.jar
    - name: Retrieve version
      run: echo "VERSION=$(grep -i '<version>' pom.xml | head -1 | sed 's/<version>//g' | sed 's/<\/version>//g' | awk '{print $1}')" >> $GITHUB_ENV
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: feedsclient-${{env.VERSION}}.jar
        path: target/*.jar
    - name: Retrieve changelog line
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "CHANGELOGLINE=$(grep -n 'FeedsClient' CHANGELOG.md | cut -d ':' -f 1 | awk 'NR==2')" >> $GITHUB_ENV
    - name: Generate changelog
      if: startsWith(github.ref, 'refs/tags/')
      run: awk "NR < ${{env.CHANGELOGLINE}}" CHANGELOG.md > CHANGELOG-${{env.VERSION}}.md
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: CHANGELOG-${{env.VERSION}}.md
        files: target/feedsclient-${{env.VERSION}}.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
